const fs = require('fs');
const path = require('path');

const BASE_URL = 'https://cordeviadigital.com';
const TODAY = new Date().toISOString().split('T')[0];

function escapeXml(unsafe) {
  return (unsafe || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

// Read brand data
const brandDataFile = path.join(__dirname, '../src/data/brandData.ts');
let blogSlugs = ['how-to-optimize-for-google-ai-overviews-2026'];
let serviceIds = ['youtube-growth', 'web-development', 'seo-mastery', 'social-media', 'brand-identity', 'it-solutions'];
let productIds = ['prod-gemini-18m-pro', 'prod-yt-kit', 'prod-seo-audit', 'prod-saas-ui', 'prod-brand-starter', 'prod-funnel-system'];

try {
  const content = fs.readFileSync(brandDataFile, 'utf8');
  
  // Extract blog slugs
  const slugMatches = [...content.matchAll(/slug:\s*['"]([^'"]+)['"]/g)].map(m => m[1]);
  if (slugMatches.length > 0) {
    blogSlugs = slugMatches.filter(s => s !== 'all' && !s.includes('category') && !s.includes('strategy'));
  }
} catch (err) {
  console.log('Using default slugs for sitemap generation');
}

const entries = [
  // Core routes
  { loc: `${BASE_URL}/`, lastmod: TODAY, changefreq: 'daily', priority: '1.00', image: `${BASE_URL}/favicon.svg`, title: 'Cordevia Digital' },
  { loc: `${BASE_URL}/services`, lastmod: TODAY, changefreq: 'weekly', priority: '0.95' },
  { loc: `${BASE_URL}/blog`, lastmod: TODAY, changefreq: 'daily', priority: '0.90' },
  { loc: `${BASE_URL}/marketplace`, lastmod: TODAY, changefreq: 'weekly', priority: '0.90' },
  { loc: `${BASE_URL}/about`, lastmod: TODAY, changefreq: 'monthly', priority: '0.80' },
  { loc: `${BASE_URL}/contact`, lastmod: TODAY, changefreq: 'monthly', priority: '0.85' },
  { loc: `${BASE_URL}/seo-console`, lastmod: TODAY, changefreq: 'weekly', priority: '0.80' },
  { loc: `${BASE_URL}/privacy`, lastmod: TODAY, changefreq: 'monthly', priority: '0.60' },
  { loc: `${BASE_URL}/terms`, lastmod: TODAY, changefreq: 'monthly', priority: '0.60' },
  { loc: `${BASE_URL}/disclosure`, lastmod: TODAY, changefreq: 'monthly', priority: '0.60' },
  { loc: `${BASE_URL}/dmca`, lastmod: TODAY, changefreq: 'monthly', priority: '0.50' },
];

// Blog posts
blogSlugs.forEach(slug => {
  entries.push({
    loc: `${BASE_URL}/blog/${slug}`,
    lastmod: TODAY,
    changefreq: 'weekly',
    priority: '0.90',
    image: `${BASE_URL}/favicon.svg`,
    title: slug.replace(/-/g, ' ')
  });
});

// Services
serviceIds.forEach(id => {
  entries.push({
    loc: `${BASE_URL}/services#${id}`,
    lastmod: TODAY,
    changefreq: 'weekly',
    priority: '0.85'
  });
});

// Marketplace products
productIds.forEach(id => {
  entries.push({
    loc: `${BASE_URL}/marketplace#${id}`,
    lastmod: TODAY,
    changefreq: 'weekly',
    priority: '0.80'
  });
});

// Build XML
const xmlUrls = entries.map(entry => {
  let item = `  <url>\n    <loc>${escapeXml(entry.loc)}</loc>\n    <lastmod>${entry.lastmod}</lastmod>\n    <changefreq>${entry.changefreq}</changefreq>\n    <priority>${entry.priority}</priority>`;
  if (entry.image) {
    item += `\n    <image:image>\n      <image:loc>${escapeXml(entry.image)}</image:loc>\n      <image:title>${escapeXml(entry.title || 'Cordevia Digital')}</image:title>\n    </image:image>`;
  }
  item += `\n  </url>`;
  return item;
}).join('\n');

const sitemapXml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
        http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd
        http://www.google.com/schemas/sitemap-image/1.1
        http://www.google.com/schemas/sitemap-image/1.1/sitemap-image.xsd">
<!-- Generated by Cordevia Digital Automated XML Sitemap Engine -->
<!-- Total Indexed URLs: ${entries.length} | Generated: ${new Date().toISOString()} -->
${xmlUrls}
</urlset>`;

const robotsTxt = `# Cordevia Digital Robots.txt
# Fully optimized for Googlebot, AdsBot-Google, Bingbot, and AI Search Crawlers

User-agent: *
Allow: /
Allow: /services
Allow: /blog
Allow: /marketplace
Allow: /about
Allow: /contact
Allow: /privacy
Allow: /terms
Allow: /disclosure
Allow: /dmca
Allow: /seo-console
Disallow: /api/
Disallow: /*?*filter=
Disallow: /*?*sort=

# Googlebot specific directives
User-agent: Googlebot
Allow: /
Allow: /*.js$
Allow: /*.css$
Allow: /*.png$
Allow: /*.jpg$
Allow: /*.svg$
Allow: /*.webp$

# Google AdSense Crawler
User-agent: Mediapartners-Google
Allow: /

# Google Ads Quality Crawler
User-agent: AdsBot-Google
Allow: /

# Canonical Sitemap Declaration
Sitemap: ${BASE_URL}/sitemap.xml
`;

const adsTxt = `# Cordevia Digital Authorized Digital Sellers (ads.txt)
# Google AdSense Authorized Publisher Declaration
# Documentation: https://support.google.com/adsense/answer/7532444

google.com, pub-9204859182740192, DIRECT, f08c47fec0942fa0

# Contact info for ad inventory verification
contact=hello@cordeviadigital.com
subdomain=cordeviadigital.com
`;

const publicDir = path.join(__dirname, '../public');
if (!fs.existsSync(publicDir)) {
  fs.mkdirSync(publicDir, { recursive: true });
}

fs.writeFileSync(path.join(publicDir, 'sitemap.xml'), sitemapXml, 'utf8');
fs.writeFileSync(path.join(publicDir, 'robots.txt'), robotsTxt, 'utf8');
fs.writeFileSync(path.join(publicDir, 'ads.txt'), adsTxt, 'utf8');

console.log(`✅ Successfully generated sitemap.xml (${entries.length} URLs), robots.txt, and ads.txt in public/`);
